platform :ios, '12.0'

def is_pod_binary_cache_enabled
  true
end

if is_pod_binary_cache_enabled
  plugin 'cocoapods-binary-cache'
  config_cocoapods_binary_cache(
    cache_repo: {
      "default" => {
        "remote" => "https://github.com/bigbangvn/demo-pod-binary-cache-prebuilt-libs.git",
        "local" => "~/.cocoapods-binary-cache/PrebuiltPods"
      }
    },
    prebuild_config: "Release",
    dev_pods_enabled: true
  )
end

def binary_pod(name, *args)
  if is_pod_binary_cache_enabled
    pod name, args, :binary => true
  else
    pod name, args
  end
end

target 'PodBinCacheExample' do
  use_frameworks!

  binary_pod 'pop',                               '~> 1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES' # Only work from Xcode 11
    end
  end
end
